config:
  dataset_folder: "your_data_folder"
  model_type: "resnet50"
  batch_size: 16
  num_epochs: 10
  lr: 0.0001
  outputs: "output"
  gradcam: False
  gradcam_num_images: 3
  gradcam_random_state: 29
  patience: 70
  loss_type: "focal"
  image_size: 448
  target_column: "cancer"
  num_patches: 3  # Số patch (2, 3, hoặc 4)
  arch_type: patch_resnet # patch_transformer
  freeze_backbone_except_last_n: 4  # null = không đóng băng, 0 = đóng băng tất cả, 1,2,3... = giữ lại n layer cuối
  dino_unfreeze_blocks: 2  # Giữ lại để tương thích ngược với code cũ